const ERROR_INVALID_DATA = 400;
const ERROR_UNAUTHORIZED = 401;
const ERROR_NOT_FOUND = 404;
const ERROR_NON_UNIQUE_DATA = 409;
const ERROR_SERVER = 500;

module.exports = {
  ERROR_INVALID_DATA,
  ERROR_NON_UNIQUE_DATA,
  ERROR_UNAUTHORIZED,
  ERROR_NOT_FOUND,
  ERROR_SERVER,
};
